version: '3.9'
services:
  zoo1:
    image: zookeeper:3.4.9
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
        - ZOO_MY_ID=1
        - ZOO_PORT=2181
        - ZOO_SERVERS=server.1=zoo1:2888:3888

  kafka1:
    image: confluentinc/cp-kafka:5.2.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zoo1:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zoo1

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
  it-firm:
    container_name: it-firm
    image: it-firm
    build:
      context: ./it-firm
      target: development
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "3001:3000"
    environment:
      - BROKER_ADDRESS=kafka1:9092
    restart: unless-stopped
    depends_on:
      - kafka1
      - postgres
